apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: TO_OVERWRITE
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/GillesPelegrin/Demo-Deployment.git
    targetRevision: HEAD
    path: TO_OVERWRITE
  destination:
    server: https://kubernetes.default.svc
    namespace: core