apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: core

resources:
  - ../../base
  - secret/secret.yaml

images:
  - name: ghcr.io/gillespelegrin/demo-taskservice
    newTag: v1.0