apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-application
  template:
    metadata:
      labels:
        app: task-application
    spec:
      containers:
        - name: task-service
          image: ghcr.io/gillespelegrin/demo-taskservice
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: task-secret
                  key: POSTGRES_USER
                  optional: false
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-secret
                  key: POSTGRES_PASSWORD
                  optional: false
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://task-db-s.postgres.database.azure.com:5432/postgres


