apiVersion: v1
kind: Service
metadata:
  name: task-service
  labels:
    app: task-service
spec:
  selector:
    app: task-application
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
